### ISSUE TITLE
VwcLayout does not respect any settings

### ISSUE THREAD

**Issue by KB-NVM** [Vonage/vivid-react#42]
According to [Vivid storybook](https://vivid.vonage.com/?path=/story/components-layout--basic) Layout component supports settings such `column-basis` and `column-spacing` which controls how items in the grid are laid out (size of items and size of spaces between them) but the `VwcLayout` wrapper does not respect any of those settings, it always uses default ones.

In the DOM it looks like the values set in props are translated to wrong attributes: `columnbasis` vs `column-basis` and `columnspacing` vs `column-spacing`
![image](https://user-images.githubusercontent.com/40795412/164738805-ad8d2fb4-2d52-4b17-b119-226d2b953640.png)

Patch file to reproduce in vivid-react's storybook:
[VwcLayout.txt](https://github.com/Vonage/vivid-react/files/8541922/VwcLayout.txt)

**Comment by k-paxian** [comment]
Fixed since `v2.10.15`
